name: Android CI with Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -f deploy.Dockerfile . -t android-build-env

      - name: Run Build in Docker Container
        run: docker run --rm -v "$PWD":/app android-build-env /bin/sh -c "./gradlew build"
